import React from 'react';
import "./description.css"
function Description(){
    return(
        <div>
        <div>
        <h1 align="center">IVY Resort</h1>
        <img  class="image" src = "https://media-cdn.tripadvisor.com/media/photo-s/0a/e4/ad/65/ivytop.jpg"/>
        <p align="center" class="text">Nestled in the foothills of majestic Himalayas, Ivy Top is situated in Srinagar Garhwal. The property is at a distance of 121 km from Jolly Grant Airport while Haridwar Junction is 130 km and Sumari Bus Stand is 12.2 km away. Guests can visit various scenic beauties such as Badrinath, Kedarnath, Hemkund Sahib, Auli, Valley of Flowers and many other notable spots during their stay. The hotel stands elegant with a beautiful yet contemporary facade, well-manicured lush green lawn and garden. For a relaxed stay an array of facilities are offered such as room service, parking and front desk for the convenience of guests. Furthermore self cooking facilities also exists to give a home away home feeling to the guest. The rooms in the hotel are uniquely designed with cozy interiors and offer exclusive amenities such as television, telephone, hot/cold water, attached bathroom and various other essential bathroom toiletries. The property houses a restaurant that serves a wide range of tantalizing dishes to suit all palates. Guests can dine and spend time with their loved ones. his resort, akin to a heritage hotel, nestles on a hillock 1km away from Srinagar Township, which has been carved out by two generations offorestersto retain the traditional values, yet is contemporary to suit modern day living. The traditional himalayan cottage tranquil environs are suited to diverse travellers from nature lovers, pilgrims, travellers, painters and bird watchers to couples on a honeymoon! The premises unfold an incredible panorama: silent and blissful peace of the Himalayan mountains, snow peaks and a 12km view of the Ganges river meandering artistically through the splendid open valley and township -a dreamland. The premises have been continuously functioning for the last 50 years towards an Eco-Friendly and biodiverse environment by way of raising more than 250 plant species, including rare plants, Rose Garden, Forest and Fruit Trees, Shrubs, Climbers, Annuals & Vegetable Garden and Lawn. One can taste the fresh fruits directly form the trees in season. The fruits include Peaches, Leechis, Mangoes, Apples, Apricots, Grapes, Kiwi, Pecanut, etc. This resort believes in paying personal attention to the finest details to make your stay a truly memorable one. We meet as strangers and depart with friendly feelings. There are various activities that are available to engage you. Should you require any further information then please feel free to us at any time and we shall be very happy to provide you with the same. Ease out and have a lovely stay at Ivy Top!</p>
        <a align="center" href = "https://www.google.com/maps/place/IvyTop+Resort/@30.2169761,78.7958977,15z/data=!4m18!1m9!3m8!1s0x0:0xc58eff7e24302019!2sIvyTop+Resort!5m2!4m1!1i2!8m2!3d30.2169761!4d78.7958977!3m7!1s0x0:0xc58eff7e24302019!5m2!4m1!1i2!8m2!3d30.2169761!4d78.7958977" target = "_blank"><h3>Directions</h3></a>
        </div>
        <div>
        <h1 align="center">Ganga Darshan</h1>
        <img class="image" src = "https://i.ytimg.com/vi/Gv9FbOxft-E/maxresdefault.jpg"/>
        <p align="center" class="text" >Nestled in the foothills of majestic Himalayas, Ivy Top is situated in Srinagar Garhwal. The property is at a distance of 121 km from Jolly Grant Airport while Haridwar Junction is 130 km and Sumari Bus Stand is 12.2 km away. Guests can visit various scenic beauties such as Badrinath, Kedarnath, Hemkund Sahib, Auli, Valley of Flowers and many other notable spots during their stay. The hotel stands elegant with a beautiful yet contemporary facade, well-manicured lush green lawn and garden. For a relaxed stay an array of facilities are offered such as room service, parking and front desk for the convenience of guests. Furthermore self cooking facilities also exists to give a home away home feeling to the guest. The rooms in the hotel are uniquely designed with cozy interiors and offer exclusive amenities such as television, telephone, hot/cold water, attached bathroom and various other essential bathroom toiletries. The property houses a restaurant that serves a wide range of tantalizing dishes to suit all palates. Guests can dine and spend time with their loved ones. his resort, akin to a heritage hotel, nestles on a hillock 1km away from Srinagar Township, which has been carved out by two generations offorestersto retain the traditional values, yet is contemporary to suit modern day living. The traditional himalayan cottage tranquil environs are suited to diverse travellers from nature lovers, pilgrims, travellers, painters and bird watchers to couples on a honeymoon! The premises unfold an incredible panorama: silent and blissful peace of the Himalayan mountains, snow peaks and a 12km view of the Ganges river meandering artistically through the splendid open valley and township -a dreamland. The premises have been continuously functioning for the last 50 years towards an Eco-Friendly and biodiverse environment by way of raising more than 250 plant species, including rare plants, Rose Garden, Forest and Fruit Trees, Shrubs, Climbers, Annuals & Vegetable Garden and Lawn. One can taste the fresh fruits directly form the trees in season. The fruits include Peaches, Leechis, Mangoes, Apples, Apricots, Grapes, Kiwi, Pecanut, etc. This resort believes in paying personal attention to the finest details to make your stay a truly memorable one. We meet as strangers and depart with friendly feelings. There are various activities that are available to engage you. Should you require any further information then please feel free to us at any time and we shall be very happy to provide you with the same. Ease out and have a lovely stay at Ivy Top!</p>
        <a align="center" href = "https://goo.gl/maps/vv1dQrzNxe6AxGkDA" target = "_blank"><h3>Directions</h3></a>
        </div>
        <div>
        <h1 align="center">Dhari Devi</h1>
        <img class="image" src = "https://thumbs.dreamstime.com/b/indian-traditional-water-temple-home-god-hi-tech-switched-uttarakhand-dhari-devi-useful-meditation-full-169521582.jpg"/>
        <p align="center" class="text" >Nestled in the foothills of majestic Himalayas, Ivy Top is situated in Srinagar Garhwal. The property is at a distance of 121 km from Jolly Grant Airport while Haridwar Junction is 130 km and Sumari Bus Stand is 12.2 km away. Guests can visit various scenic beauties such as Badrinath, Kedarnath, Hemkund Sahib, Auli, Valley of Flowers and many other notable spots during their stay. The hotel stands elegant with a beautiful yet contemporary facade, well-manicured lush green lawn and garden. For a relaxed stay an array of facilities are offered such as room service, parking and front desk for the convenience of guests. Furthermore self cooking facilities also exists to give a home away home feeling to the guest. The rooms in the hotel are uniquely designed with cozy interiors and offer exclusive amenities such as television, telephone, hot/cold water, attached bathroom and various other essential bathroom toiletries. The property houses a restaurant that serves a wide range of tantalizing dishes to suit all palates. Guests can dine and spend time with their loved ones. his resort, akin to a heritage hotel, nestles on a hillock 1km away from Srinagar Township, which has been carved out by two generations offorestersto retain the traditional values, yet is contemporary to suit modern day living. The traditional himalayan cottage tranquil environs are suited to diverse travellers from nature lovers, pilgrims, travellers, painters and bird watchers to couples on a honeymoon! The premises unfold an incredible panorama: silent and blissful peace of the Himalayan mountains, snow peaks and a 12km view of the Ganges river meandering artistically through the splendid open valley and township -a dreamland. The premises have been continuously functioning for the last 50 years towards an Eco-Friendly and biodiverse environment by way of raising more than 250 plant species, including rare plants, Rose Garden, Forest and Fruit Trees, Shrubs, Climbers, Annuals & Vegetable Garden and Lawn. One can taste the fresh fruits directly form the trees in season. The fruits include Peaches, Leechis, Mangoes, Apples, Apricots, Grapes, Kiwi, Pecanut, etc. This resort believes in paying personal attention to the finest details to make your stay a truly memorable one. We meet as strangers and depart with friendly feelings. There are various activities that are available to engage you. Should you require any further information then please feel free to us at any time and we shall be very happy to provide you with the same. Ease out and have a lovely stay at Ivy Top!</p>
        <a align="center" href = "https://www.google.com/maps/place/Dhari+Devi+Temple+Dang+Chaura/@30.2586127,78.8743367,17.1z/data=!4m12!1m6!3m5!1s0x3909b0672cf98fb7:0x74f4634919ccbcab!2sDhari+Devi+Temple+Dang+Chaura!8m2!3d30.2578726!4d78.8773362!3m4!1s0x3909b0672cf98fb7:0x74f4634919ccbcab!8m2!3d30.2578726!4d78.8773362" target = "_blank"><h3>Directions</h3></a>
        </div>
        <div>
        <h1 align="center">Khirsu</h1>
        <img class="image" src = "https://tourismnewslive.com/wp-content/uploads/2019/01/Khirsu_Uttarakhand.jpg"/>
        <p align="center" class="text" >Nestled in the foothills of majestic Himalayas, Ivy Top is situated in Srinagar Garhwal. The property is at a distance of 121 km from Jolly Grant Airport while Haridwar Junction is 130 km and Sumari Bus Stand is 12.2 km away. Guests can visit various scenic beauties such as Badrinath, Kedarnath, Hemkund Sahib, Auli, Valley of Flowers and many other notable spots during their stay. The hotel stands elegant with a beautiful yet contemporary facade, well-manicured lush green lawn and garden. For a relaxed stay an array of facilities are offered such as room service, parking and front desk for the convenience of guests. Furthermore self cooking facilities also exists to give a home away home feeling to the guest. The rooms in the hotel are uniquely designed with cozy interiors and offer exclusive amenities such as television, telephone, hot/cold water, attached bathroom and various other essential bathroom toiletries. The property houses a restaurant that serves a wide range of tantalizing dishes to suit all palates. Guests can dine and spend time with their loved ones. his resort, akin to a heritage hotel, nestles on a hillock 1km away from Srinagar Township, which has been carved out by two generations offorestersto retain the traditional values, yet is contemporary to suit modern day living. The traditional himalayan cottage tranquil environs are suited to diverse travellers from nature lovers, pilgrims, travellers, painters and bird watchers to couples on a honeymoon! The premises unfold an incredible panorama: silent and blissful peace of the Himalayan mountains, snow peaks and a 12km view of the Ganges river meandering artistically through the splendid open valley and township -a dreamland. The premises have been continuously functioning for the last 50 years towards an Eco-Friendly and biodiverse environment by way of raising more than 250 plant species, including rare plants, Rose Garden, Forest and Fruit Trees, Shrubs, Climbers, Annuals & Vegetable Garden and Lawn. One can taste the fresh fruits directly form the trees in season. The fruits include Peaches, Leechis, Mangoes, Apples, Apricots, Grapes, Kiwi, Pecanut, etc. This resort believes in paying personal attention to the finest details to make your stay a truly memorable one. We meet as strangers and depart with friendly feelings. There are various activities that are available to engage you. Should you require any further information then please feel free to us at any time and we shall be very happy to provide you with the same. Ease out and have a lovely stay at Ivy Top!</p>
        <a align="center" href = "https://goo.gl/maps/nh5WEbiLX4b8iHsR7" target = "_blank"><h3>Directions</h3></a>
        </div>
        <div>
        <h1 align="center">Alaknanda Ghat</h1>
        <img class="image" src = "https://i.ytimg.com/vi/brhkgptex9A/maxresdefault.jpg"/>
        <p align="center" class="text" >Nestled in the foothills of majestic Himalayas, Ivy Top is situated in Srinagar Garhwal. The property is at a distance of 121 km from Jolly Grant Airport while Haridwar Junction is 130 km and Sumari Bus Stand is 12.2 km away. Guests can visit various scenic beauties such as Badrinath, Kedarnath, Hemkund Sahib, Auli, Valley of Flowers and many other notable spots during their stay. The hotel stands elegant with a beautiful yet contemporary facade, well-manicured lush green lawn and garden. For a relaxed stay an array of facilities are offered such as room service, parking and front desk for the convenience of guests. Furthermore self cooking facilities also exists to give a home away home feeling to the guest. The rooms in the hotel are uniquely designed with cozy interiors and offer exclusive amenities such as television, telephone, hot/cold water, attached bathroom and various other essential bathroom toiletries. The property houses a restaurant that serves a wide range of tantalizing dishes to suit all palates. Guests can dine and spend time with their loved ones. his resort, akin to a heritage hotel, nestles on a hillock 1km away from Srinagar Township, which has been carved out by two generations offorestersto retain the traditional values, yet is contemporary to suit modern day living. The traditional himalayan cottage tranquil environs are suited to diverse travellers from nature lovers, pilgrims, travellers, painters and bird watchers to couples on a honeymoon! The premises unfold an incredible panorama: silent and blissful peace of the Himalayan mountains, snow peaks and a 12km view of the Ganges river meandering artistically through the splendid open valley and township -a dreamland. The premises have been continuously functioning for the last 50 years towards an Eco-Friendly and biodiverse environment by way of raising more than 250 plant species, including rare plants, Rose Garden, Forest and Fruit Trees, Shrubs, Climbers, Annuals & Vegetable Garden and Lawn. One can taste the fresh fruits directly form the trees in season. The fruits include Peaches, Leechis, Mangoes, Apples, Apricots, Grapes, Kiwi, Pecanut, etc. This resort believes in paying personal attention to the finest details to make your stay a truly memorable one. We meet as strangers and depart with friendly feelings. There are various activities that are available to engage you. Should you require any further information then please feel free to us at any time and we shall be very happy to provide you with the same. Ease out and have a lovely stay at Ivy Top!</p>
        <a align="center" href = "https://www.google.com/maps/place/Dhari+Devi+Temple+Dang+Chaura/@30.2586127,78.8743367,17.1z/data=!4m12!1m6!3m5!1s0x3909b0672cf98fb7:0x74f4634919ccbcab!2sDhari+Devi+Temple+Dang+Chaura!8m2!3d30.2578726!4d78.8773362!3m4!1s0x3909b0672cf98fb7:0x74f4634919ccbcab!8m2!3d30.2578726!4d78.8773362" target = "_blank"><h3>Directions</h3></a>
        </div>
        </div>
    );
}
export default Description;